### ISSUE TITLE
Stale data when refreshing Contract Overview page

### ISSUE THREAD

**Issue by Jbekker** [VoiNetwork/staking-www#26]
Stale data when refreshing [Contract Overview page](https://staking.voi.network/overview)

To reproduce:
1. Have 2 or more contracts
2. Select the 2nd contract
3. Refresh the page (F5)
4. Notice that the balance and other data of the 2nd contract is shown but the first contract is selected.

**Comment by temptemp3** [comment]
Thanks for reporting the issue! We'll roll this fix into a release soon. Thx!

**Comment by temptemp3** [comment]
Ended up fixing this one. The issue was the the tabs would show the first item selected even though another contract may have been active.

**Comment by temptemp3** [comment]
@Jbekker can you have another look. We just pushed out a new release.

**Comment by Jbekker** [comment]
Thanks, works great!
