### ISSUE TITLE
Prefill the parent address when clicking Earn Block Rewards

### ISSUE THREAD

**Issue by Jbekker** [VoiNetwork/staking-www#27]
When clicking the `Earn Block Rewards` button on the [Contract Overview page](https://staking.voi.network/overview), it would be helpful to have the `Parent Address` field prefilled with the Contract Account.
Especially since Withdraw / Deposit is also in the context of the selected contract, you would expect to be the same for `Earn Block Rewards`.

**Comment by temptemp3** [comment]
<img width="833" alt="Screenshot 2024-10-02 at 22 47 55" src="https://github.com/user-attachments/assets/b81d8a85-41e5-452e-ad2f-d2527cffebde">

**Comment by temptemp3** [comment]
@Jbekker thank you for the feedback! In this next, we will be providing an easy way to renew keys for voi swarm users in additional to advanced instructions that is more guided than before. I will make sure parent address is prefilled in this case. Thx!

**Comment by temptemp3** [comment]
<img width="855" alt="Screenshot 2024-10-02 at 22 52 22" src="https://github.com/user-attachments/assets/19307b75-bf8c-4b6f-a552-59b792c06664">

**Comment by Jbekker** [comment]
That looks like a great improvement!

**Comment by temptemp3** [comment]
https://drive.google.com/file/d/1gImSTdiI-VJloFHuEab1kl7FOxluaTs5/view?usp=drive_link

**Comment by temptemp3** [comment]
Thx should be available by tomorrow ; )

**Comment by temptemp3** [comment]
@Jbekker can you have another look. We just pushed out a new release.

**Comment by Jbekker** [comment]
Thanks! I like the updates, nothing to complain about it at the moment :-)
