### ISSUE TITLE
Advanced Earn Block Rewards paste from clipboard button

### ISSUE THREAD

**Issue by temptemp3** [VoiNetwork/staking-www#37]
<img width="1024" alt="Screenshot 2024-10-04 at 11 33 44" src="https://github.com/user-attachments/assets/7f8e04b6-587d-47f5-8d6d-f2a0458ec59f">

For Advanced Earn Block Rewards add button to paste from clipboard similar to Algo Tools

Snippet

```
async function pasteFromClipboard() {
  const clip = await navigator.clipboard.readText();
  part.value.voteFirst = Number(clip.match(/(?<=^First\sround:\s*)\d*$/gm)![0]);
  part.value.voteLast = Number(clip.match(/(?<=^Last\sround:\s*)\d*$/gm)![0]);
  part.value.voteKeyDilution = Number(
    clip.match(/(?<=^Key\sdilution:\s*)\d*$/gm)![0],
  );
  part.value.selectionKey = clip.match(/(?<=^Selection\skey:\s*)[^\s]*$/gm)![0];
  part.value.voteKey = clip.match(/(?<=^Voting\skey:\s*)[^\s]*$/gm)![0];
  part.value.stateProofKey = clip.match(
    /(?<=^State\sproof\skey:\s*)[^\s]*$/gm,
  )![0];
}
```

More info: <https://github.com/GalaxyPay/algo-tools>

**Comment by prince-hope1975** [comment]
![image](https://github.com/user-attachments/assets/71463634-9daf-4016-88b7-b0a23bf80e28)
The image doesn't show up on my end, but I am assuming this is what you're talking about
